# Configuration for actions/labeler
# Automatically label PRs based on file paths

"📱 frontend":
  - changed-files:
      - any-glob-to-any-file: "src/app/**/*"
  - changed-files:
      - any-glob-to-any-file: "src/ui/**/*"

"🎨 styling":
  - changed-files:
      - any-glob-to-any-file: "**/*.css"
  - changed-files:
      - any-glob-to-any-file: "**/tailwind.config.*"
  - changed-files:
      - any-glob-to-any-file: "**/postcss.config.*"

"📦 dependencies":
  - changed-files:
      - any-glob-to-any-file: "package.json"
  - changed-files:
      - any-glob-to-any-file: "pnpm-lock.yaml"

"🔧 config":
  - changed-files:
      - any-glob-to-any-file: "*.config.*"
  - changed-files:
      - any-glob-to-any-file: "eslint.config.*"
  - changed-files:
      - any-glob-to-any-file: "prettier.config.*"
  - changed-files:
      - any-glob-to-any-file: "commitlint.config.*"
  - changed-files:
      - any-glob-to-any-file: "next.config.*"

"📚 documentation":
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

"🔄 workflows":
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

"📄 content":
  - changed-files:
      - any-glob-to-any-file: "src/content/**/*"
