import "./globals.css";
import { getCurrentUser } from "@/app/_lib/auth/server";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Amra - Love app",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
