import "./globals.css";
import { getCurrentUser } from "@/app/_lib/auth/server";
import { redirect } from "next/navigation";
import { ramona } from "@/app/_fonts";

export const metadata = {
  title: "Amra - Love app",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  themeColor: "#ffffff",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Amra",
  },
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
      </head>
      <body className={`${ramona.variable} antialiased`}>{children}</body>
    </html>
  );
}
